addReviewers: true

reviewers:
    - EGNKupava
    - Heymdall
    - IBelyaev
    - aweppc
    - Artess999
    - stepancar
    - NatalyaZ
    - YozhEzhi
    - denisx

skipKeywords:
    - wip

numberOfReviewers: 0
