addReviewers: true

reviewers:
    - stepancar
    - FenkoAlex
    - raylyanway
    - ilatovsky
    - aweppc
    - IBelyaev
    - 7rulnik
    - pavelozavr
    - denisx
    - vorozhtsoff

skipKeywords:
    - wip
