addReviewers: true

reviewers:
    - stepancar
    - Heymdall
    - IBelyaev
    - aweppc
    - Artess999
    - aso1datov
    - FenkoAlex
    - NatalyaZ
    - raylyanway
    - YozhEzhi
    - denisx
    - vorozhtsoff

skipKeywords:
    - wip

numberOfReviewers: 0
