name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      CI: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn --pure-lockfile

      - name: Build app
        run: yarn build
        env:
          BUILD_CONCURRENCY: 5

      - name: Set NPM Token
        uses: filipstefansson/set-npm-token-action@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Set Github credentials
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          name: 'semantic-release-bot'
          email: 'semantic-release-bot@martynus.net'
          token: '${{ secrets.PERMISSION_GITHUB_TOKEN }}'

      - name: Publish
        run: yarn pub:ci
        env:
          GITHUB_TOKEN: ${{ secrets.PERMISSION_GITHUB_TOKEN }}
